os: windows
language: cpp

env:
    - CMAKE_GENERATOR='Visual Studio 12 2013 Win64'

script:
    - git clone https://github.com/andre-schulz/mve.git
    - cd mve
    - git checkout remotes/origin/cmake
    - cmake 3rdparty
    - msbuild 3rdparty.sln /target:Release
    - cd ../
    - cmake mve
    - msbuild MVE.sln /target:Release
    - cmake --build . --target PACKAGE
