os: windows
language: cpp

env:
    - CMAKE_GENERATOR='Visual Studio 15 2017 Win64' 
  
script:
     - git clone https://github.com/lyonzy/mve.git
     - cd mve
     - git checkout remotes/origin/cmake
     - cd 3rdparty
     - cmake .
     - cmake --build . --config Release
     - cd ..
     - cmake .
     - cmake --build . --config Release
     - cmake --build . --target PACKAGE --config Release
