# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
  timeoutInMinutes: 0

jobs:
  - job: BuildMVE
    timeoutInMinutes: 90
    steps:
    - script: |
        rem cmake --help
        set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
        set CMAKE_GENERATOR_TOOLSET=host=x64
        git clone https://github.com/andre-schulz/mve.git
        cd mve
        git checkout remotes/origin/cmake
        cd 3rdparty
        cmake .
        cmake --build . --config Release
        cd ..
        cmake .
        cmake --build . --config Release
        cmake --build . --target PACKAGE --config Release
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'mve/MVE-0.1.1-win64.zip'
        artifactName: MVE
