# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    rem cmake --help
    set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
    set MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
    set CMAKE_MAKE_PROGRAM=%MSBUILD_PATH%
    git clone https://github.com/lyonzy/mve.git
    cd mve
    git checkout remotes/origin/cmake
    cmake 3rdparty
    rem %MSBUILD_PATH%\msbuild.exe 3rdparty.sln /property:Configuration=Release /maxcpucount /property:BuildInParallel=true
    cd ..
    dir
    cd mve
    cmake .
    tree /F
    %MSBUILD_PATH%\msbuild.exe mve.sln /property:Configuration=Release /maxcpucount /property:BuildInParallel=true
    cmake --build . --target PACKAGE
  displayName: 'Build MVE'
