# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    rem cmake --help
    set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
    set CMAKE_GENERATOR_TOOLSET=host=x64
    set MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
    git clone https://github.com/andre-schulz/mve.git
    cd mve
    git checkout remotes/origin/cmake
    cmake 3rdparty
    cmake --build 3rdparty --config Release
    cmake .
    cmake --build . --config Release
    rem tree /F
    rem cmake --build . --target PACKAGE
    rem tree /F
  displayName: 'Build MVE'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'mve/'
    artifactName: MVE
