# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    set CMAKE_GENERATOR='Visual Studio 15 2017 Win64' 
    set MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    export PATH=$MSBUILD_PATH:$PATH
    git clone https://github.com/andre-schulz/mve.git
    cd mve
    git checkout remotes/origin/cmake
    cmake 3rdparty
    msbuild.exe 3rdparty.sln /property:Configuration=Release /maxcpucount /property:BuildInParallel=true
    cd ../
    cmake mve
    msbuild.exe MVE.sln /property:Configuration=Release /maxcpucount /property:BuildInParallel=true
    cmake --build . --target PACKAGE
  displayName: 'Build MVE'
